spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://edmindev:mldnjava@eureka-7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true

info:
  app:
    name: mldn-microcloud
    version: v1.0.0
  company:
    name: www.mldn.cn
  pom:
    artifactId: $project.artifactId$
    version: $project.version$

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.bjsxt.vo
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mldn8001?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: '{cipher}AQBA8kprBwxcf6vhvOkzoNuZnQ7RT05RKj8SEPpfFkA7aW6KockWMMChhQoHNd3QKp0y8nEHZh4zrdQufhlKdtG3nsuvvZ+VaAs8HpB2aQOP0+a7rT001SWB7MexML1lfnM/1F2FxSgYwPBCQRAG2WHofeMdXBhAbXJEnHlIkPnYR1xQyrElDqzkMrOwzNQD92SHYjCam2ObhD1M8QuXGE6pNaMTPkFXx0hyQoMi3iHm5itbhjbE67FguJUf+TmdtF7DCGttlBdFWY0fE78Pj8z91oY7VRoOgDlAQxIYyHMRh5NTBEjYwOLItiU5qaSx4YM10HGOPE/mtP1d4khhf2WRpVZmjSKwcPImlltJhG7amIL43LGf1wv/lJwBAsZZ6vY='
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  application:
    name: microcloud-config-dept-client
---
server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://edminbeta:mldnjava@eureka-7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true

info:
  app:
    name: mldn-microcloud
    version: v1.0.0
  company:
    name: www.mldn.cn
  pom:
    artifactId: $project.artifactId$
    version: $project.version$

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.bjsxt.vo
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  profiles: beta
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mldn8001?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: '{cipher}AQBA8kprBwxcf6vhvOkzoNuZnQ7RT05RKj8SEPpfFkA7aW6KockWMMChhQoHNd3QKp0y8nEHZh4zrdQufhlKdtG3nsuvvZ+VaAs8HpB2aQOP0+a7rT001SWB7MexML1lfnM/1F2FxSgYwPBCQRAG2WHofeMdXBhAbXJEnHlIkPnYR1xQyrElDqzkMrOwzNQD92SHYjCam2ObhD1M8QuXGE6pNaMTPkFXx0hyQoMi3iHm5itbhjbE67FguJUf+TmdtF7DCGttlBdFWY0fE78Pj8z91oY7VRoOgDlAQxIYyHMRh5NTBEjYwOLItiU5qaSx4YM10HGOPE/mtP1d4khhf2WRpVZmjSKwcPImlltJhG7amIL43LGf1wv/lJwBAsZZ6vY='
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  application:
    name: microcloud-config-dept-client