spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://edmindev:mldnjava@eureka-7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true

info:
  app:
    name: mldn-microcloud
    version: v1.0.0
  company:
    name: www.mldn.cn
  pom:
    artifactId: $project.artifactId$
    version: $project.version$

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.bjsxt.vo
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mldn8001?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: '{cipher}61b3750d3665410d4fedb73a1ca859afa154bbc83cb5434096870051cac09203'
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  application:
    name: microcloud-config-dept-client
---
server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://edminbeta:mldnjava@eureka-7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com
    prefer-ip-address: true

info:
  app:
    name: mldn-microcloud
    version: v1.0.0
  company:
    name: www.mldn.cn
  pom:
    artifactId: $project.artifactId$
    version: $project.version$

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.bjsxt.vo
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  profiles: beta
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mldn8001?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: '{cipher}61b3750d3665410d4fedb73a1ca859afa154bbc83cb5434096870051cac09203'
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  application:
    name: microcloud-config-dept-client